# This is a basic workflow to help you get started with Actions

name: Arduino Lint

env:
  GITHUB_WORKSPACE = /home/runner/work/Ultrasonic_piano

# Controls when the workflow will run
on: 
  [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: arduino/arduino-lint-action@v1.0.1
